tst_rast: tst_rast.o raster.o 
	cc68x -g tst_rast.o raster.o -o tst_rast

tst_mod: tst_mod.o model.o mod_asm.o
	cc68x -g tst_mod.o model.o mod_asm.o -o tst_mod
	
tst_rend: tst_rend.o renderer.o rend_asm.o raster.o model.o mod_asm.o
	cc68x -g tst_rend.o renderer.o rend_asm.o raster.o model.o mod_asm.o -o tst_rend
	
tst_inp: tst_inp.o
	cc68x -g tst_inp.o -o tst_inpt

tst_inp.o: tst_inp.c
	cc68x -g -c tst_inp.c

tst_rend.o: tst_rend.c renderer.h model.h
	cc68x -g -c tst_rend.c

tst_mod.o: tst_mod.c model.h
	cc68x -g -c tst_mod.c
	
tetris: tet_main.o model.o renderer.o rend_asm.o tvnt_hnd.o input.o raster.o mod_asm.o 
	cc68x -g tet_main.o model.o renderer.o rend_asm.o tvnt_hnd.o input.o raster.o mod_asm.o -o tetris
	
tet_main.o: tet_main.c
	cc68x -g -c tet_main.c
	
tvnt_hnd.o: tvnt_hnd.h tvnt_hnd.c model.h renderer.h
	cc68x -g -c tvnt_hnd.c
	
input.o: input.h input.c
	cc68x -g -c input.c

model.o: model.c model.h
	cc68x -g -c model.c

mod_asm.o: mod_asm.s
	gen -D -L2 mod_asm.s

tst_rast.o: tst_rast.c raster.h
	cc68x -g -c tst_rast.c

raster.o: raster.c raster.h
	cc68x -g -c raster.c
	
renderer.o: renderer.c renderer.h
	cc68x -g -c renderer.c

rend_asm.o: rend_asm.s
	gen -D -L2 rend_asm.s
	
all:
	make clean
	make tetris

rast_all:
	make clean
	make tst_rast

mod_all:
	make clean
	make tst_mod
	
rend_all:
	make clean
	make tst_rend

input_all:
	make clean
	make tst_inp
	
clean:
	$(RM) -f tst_rast tst_rend tst_inp tst_mod tetris *.o
